# Site Settings
baseurl: ""
url: "https://vuetricks.click/"

# Blog Settings
theme_settings:
  title: Vue tricks - блог для обучения и развития в мире Vue.js фреймворка
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/logo.svg
    username: Vue tricks
    author: vuetricks.click
    description: Vue tricks - блог для обучения и развития в мире Vue.js фреймворка
    experience:
      - start: 2017-05-03
        end: 2018-05-06
        experience: company name, title
    skills:
      - skill: HTML5 & CSS
        value: 85  # Percent value

  # Icons
  icons:
    email: inphuman@gmail.com
    linkedin: https://www.linkedin.com/in/inphuman
    github:
    gitlab:
    bitbucket:
    telegramm: https://t.me/inphuman
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [ jekyll-paginate ]
bootstrap:
  assets: true
